import React from "react";
import NavigationHeader from "@/layout/NavigationHeader";
import {Providers} from "@/providers/providers";
import './globals.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="antialiased">
        <body className={'bg-slate-600'}>
        <Providers>
            <NavigationHeader/>
            <main className="container mx-auto p-4">
                {children}
            </main>
        </Providers>
        </body>
        </html>
    )
}
